name: Latest Blog Post

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Latest blogs from Hashnode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
      - name: Run blog post workflow
        with:
          feed_list: "https://codingadda.hashnode.dev/"
