name: Latest Blog Post Workflow

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blogs from Hashnode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Run blog post workflow
        uses: Yuvadi29/Yuvadi29/tree/main/.github/workflows/blog-post-workflow@main
        with:
          feed_list: "https://codingadda.hashnode.dev/"
