name: 📚 Blog Updater
on:
  push:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  youtube:
    name: Latest Blogs from Hashnode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "HASHNODE_BLOG"
          max_post_count: 5
          feed_list: "https://codingadda.hashnode.dev/rss.xml"
          description_max_length: 140
