name: Update README with YT data

on:
  schedule:
    - cron: '* * 14 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent YT activity

    steps:
      - name: checkput main branch
        uses: actions/checkout@v3
      - name: Update this repo's README with recent YT activity
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UChVzP7gNOlkymoo000Y9_6Q
          max_videos: 9
