name: YouTube Videos
on:
  push:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  youtube:
    name: Latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE-VIDEOS-LIST"
          max_post_count: 4
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UChVzP7gNOlkymoo000Y9_6Q"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: |
            ${{ '{%' }} if isLoop == 1 ${{ '%}' }}
            <style>
              /* Style for the table and its elements */
              table {
                width: 100%;
                border-collapse: collapse;
                margin-bottom: 20px;
              }
              td {
                padding: 10px;
                vertical-align: top;
                border-bottom: 1px solid #ddd; /* Add border between rows */
              }
              img {
                width: 180px; /* Increased thumbnail size */
                height: auto;
                display: block;
                margin-bottom: 10px;
              }
              a {
                text-decoration: none;
                color: #0366d6; /* Link color */
                font-weight: bold;
              }
              a:hover {
                text-decoration: underline; /* Underline link on hover */
              }
              .title {
                font-size: 18px;
                margin-bottom: 5px;
              }
              .description {
                font-size: 14px;
                color: #586069; /* Lighter text color for description */
              }
            </style>
            ${{ '{%' }} endif ${{ '%}' }}

            <table>
              <tbody>
                <tr>
                  <td>
                    <a href="${{ url }}">
                      <img src="https://i.ytimg.com/vi/${{ videoId }}/mqdefault.jpg" alt="${{ title }}">
                    </a>
                  </td>
                  <td>
                    <div class="title">
                      <a href="${{ url }}">${{ title }}</a>
                    </div>
                    <div class="description">
                      ${{ description }}
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          ```
          description_max_length: 140
